# Generated by Django 4.1.4 on 2022-12-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ImdbId',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
