# Generated by Django 4.1.4 on 2022-12-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_details', '0002_movie_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
