# Generated by Django 4.1.4 on 2023-01-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_details', '0003_movie_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ImdbId',
            new_name='imdbID',
        ),
    ]
