# Generated by Django 4.1.4 on 2022-12-26 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_details', '0003_movie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=user_profile.models.user_directory_path)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('completed_movies', models.ManyToManyField(related_name='completed', to='movie_details.movie')),
                ('planned_movies', models.ManyToManyField(related_name='planned', to='movie_details.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watching_movies', models.ManyToManyField(related_name='watching', to='movie_details.movie')),
            ],
        ),
    ]
